# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b817dc320cc5380bf1606ac1269c62ff0f3bfaf74ef7d2fb4d2e837490cbdfb5aed9df690195c4cbab1ecb73e685c61198dcd49d1c7fb0f727fedf6a3389701a

test:
  secret_key_base: aa8b49c8b61503679d277eb3858590789fee1c1bc3c09159a543d3971d4a4d71481392515ac352e9230a2f1383b07ededf335bbc884f657bab59e11a11a05142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
